version: '3.8'

services:
  sky-alpaca-bot:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    env_file: vars.env
    # ports:
    #   - "${LOCAL_PORT}:${LOCAL_PORT}"
    volumes:
      - .:/workspace:cached
    depends_on:
      - redis
    restart: on-failure:3
  
  dashboard:
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    env_file: vars.env
    ports:
      - "${LOCAL_PORT}:${LOCAL_PORT}"
    volumes:
      - .:/workspace:cached
    depends_on:
      - redis

  portfolio-manager:
    build:
      context: .
      dockerfile: ./PortfolioManager/Dockerfile
    env_file: vars.env
    # ports:
      # - "7845:${LOCAL_PORT}"
    volumes:
      - .:/workspace:cached
    depends_on:
      - redis
    restart: on-failure:3

  redis:
    image: redis/redis-stack-server:latest
    env_file: vars.env
    ports:
      - "${DB_PORT}:${DB_PORT}"
    hostname: "${DB_HOST}"
    volumes:
      - redis-data:/data
    restart: always
  

volumes:
  redis-data:
