# Security
API_KEY = ''
API_SECRET = ''
WEBHOOK_PASSPHRASE = ''

# Strategy Settings
REWARD = 3
BREAKEVEN = 0.85
RISK_EXPOSURE = 0.05
TAKEPROFIT_POSITION = 0.5
DAYTRADE_ALLOW= True
FRACTIONAL_ALLOW = True

# Social Hooks
DISCORD_WEBHOOK_URL = ''
DISCORD_WEBBHOOK_ENABLED = True

# Network Settings
LOCAL_HOST = '0.0.0.0'
PORT = '5000'
